name: Test, Build container
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

#      - name: Clean temp directory
#        run: cd ./bitnami/clickhouse/22.9/debian-11/

      - name: Build and push Docker images
        uses: docker/build-push-action@v1
        with:
          username: _json_key
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: playson-dev/clickhouse-bitnami/clickhouse
          tag_with_ref: true
          path: ./bitnami/clickhouse/22.9/debian-11/Dockerfile
#        working-directory: ./bitnami/clickhouse/22.9/debian-11/

